version: '3'

services:

  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=hail_ride
      - MYSQL_ROOT_PASSWORD=La bete1!
    volumes:
      - ./dbdata:/var/lib/mysql

    
    ports:
      - '3308:3306'
    expose:
      - '3308'

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/ride_on
    ports:
      - "8000:8000"
    depends_on:
      - db